version: "3.3"
services:
  dev:
    image: alpr-unconstraned
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    working_dir: /work
    ipc: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes: 
      - /media:/media
      - .cache/.vscode-server/:/home/msis_dev/.vscode-server/
    working_dir: $PWD
